B s1t03 test
agh-bit-academy/SummerProject2022 pull request #114
Opened 2022-08-05 15:21 UTC by dadamczykk

# PR Template
## Lista zmian
### Lista dodanych plików + uzasadnienie
- DATA.txt
- prog.py
- sol.py
- test_basic.py
- test_bigRand.py
- test_mediumRand.py
-

### Lista usuniętych plików + uzasadnienie
-
-

### Lista zmodyfikowanych plików + uzasadnienie
-
-

### Lista dodanych testów + opis testów
- testy podstawowe, średnie i duże do s1t03
-

### Lista usuniętych testów + uzasadnienie
-
-

### Lista zmodyfikowanych testów + uzasadnienie
-
-

## Lista Wymagań
### Ogólna lista wymagań
- [ ] flake8
- [ ] Pliki odnoszą się do odpowiedniego katalogu
- [ ] Brak "Magic Number"
- [ ] Komentarz zawierający listę autorów dla niepustych plików

### Lista wymagań dla testów
- [ ] Uruchomienie przez *core.py*
- [ ] Uruchomienie przez pytest *nazwa_pliku.py*
- [ ] Dodanie plików DATA.txt i \_\_init\_\_.py

### Lista wymagań dla plików źródłowych
- [ ] Napisanie testów dla funkcji oraz metod w klasach
- [ ] Oznaczenie otestowanych funkcji oraz metod w klasach
- [ ] Samodokumentujące się zmienne oraz funkcje
- [ ] Import *nazwa* -> from *nazwa* import *nazwa1*, *nazwa2*, ...
- [ ] Import w kolejności alfabetycznej bibliotek  

### Nazewnictwo 
- [ ] Makra -> PIERWSZE_DRUGIE_TRZECIE
- [ ] Zmienne -> pierwszeDrugieTrzecie
- [ ] Funkcje -> pierwsze_drugie_trzecie
- [ ] Klasy -> PierwszeDrugieTrzecie
- [ ] Pliki -> pierwsze_drugie_trzecie
- [ ] Katalogi -> Pierwsze_Drugie_Trzecie

### pytest
- [ ] Kolejność markerów: order -> dependency -> parametrize
- [ ] Jeżeli możliwe, markery *order* i *dependency* przy klasie
- [ ] Marker *parametrize* przy funkcji
- [ ] Pliki -> test_pierwszeDrugieTrzecie
- [ ] Funkcje -> test_pierwsze_drugie_trzecie
- [ ] Klasy -> TestPierwszeDrugieTrzecie
- [ ] Listy testów -> pierwszeDrugieTrzecieTests
- [ ] Dependency_name -> test\[*nazwa_pliku*\]_\[s..t..\]
- [ ] Nazwa funkcji zawiera analogiczny człon jak testy w markerze parametrize

2022-08-05 15:23 UTC, dadamczykk commented
Przy odpalaniu testów przez core.py wyrzuca błąd, który zgłaszał Andrzej

2022-08-05 18:48 UTC, Jullija commented on WDI/Zestaw_1/Zadanie_03/sol.py
> +def f(s):
Nie podpisałeś się :(

2022-08-05 18:50 UTC, Jullija commented on WDI/Zestaw_1/Zadanie_03/sol.py
> +def f(s):
Nie wiem, czy nie będzie problemu z wrzuceniem drugiego sol.py do mastera-B

2022-08-05 18:53 UTC, dadamczykk commented on WDI/Zestaw_1/Zadanie_03/sol.py
> +def f(s):
Przy merge powinna być opcja wybrania odpowiedniego pliku jako tego właściwego

2022-08-05 18:54 UTC, dadamczykk commented on WDI/Zestaw_1/Zadanie_03/sol.py
> +def f(s):
Już zrobione, na master-B będzie Twój sol

2022-08-05 18:57 UTC, Jullija approved these changes

2022-08-05 20:07 UTC, Rusiek requested changes
Usuń z commita .gitignore i będzie git

2022-08-05 20:07 UTC, Rusiek commented on .gitignore
> +tempCodeRunnerFile.python
Nie modyfikujemy tego pliku na repozytorium

2022-08-06 00:25 UTC, Rusiek approved these changes

2022-08-06 00:25 UTC, Rusiek approved these changes

2022-08-06 00:25 UTC, merged