A s3t09
agh-bit-academy/SummerProject2022 pull request #173
Opened 2022-08-10 12:26 UTC by socz3qqq

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-10 19:20 UTC, MadMach420 commented on WDI/Zestaw_3/Zadanie_09/sol.py
> +    if len == 0:
tu chyba if lenA == 0

2022-08-10 19:21 UTC, MadMach420 commented on WDI/Zestaw_3/Zadanie_09/sol.py
> +    if len == 0:
poza tym wydaje się git

2022-08-11 09:05 UTC, MadMach420 requested changes
Po tym już dam approve, sorry że wcześniej nie zauważyłem tamtych rzeczy do zmiany

2022-08-11 09:05 UTC, MadMach420 commented on WDI/Zestaw_3/Zadanie_09/test_basic.py
> +                      for _ in range(33)]
Jeszcze zauważyłem że tu jest for _ in range(33), to 33 chyba mieliśmy w makrze dawać

2022-08-11 09:05 UTC, MadMach420 commented on WDI/Zestaw_3/Zadanie_09/test_random.py
> +                    for _ in range(30)]
tu to samo co wyżej

2022-08-11 11:58 UTC, socz3qqq commented on WDI/Zestaw_3/Zadanie_09/test_random.py
> +                    for _ in range(30)]
okej poprawione, dziena

2022-08-11 22:23 UTC, Kasl0 approved these changes

2022-08-12 06:22 UTC, kkkucia approved these changes

2022-08-12 09:31 UTC, akarcinski approved these changes

2022-08-12 12:51 UTC, MadMach420 approved these changes

2022-08-12 12:51 UTC, merged