fixed problems
agh-bit-academy/SummerProject2022 pull request #187
Opened 2022-08-10 22:55 UTC by krzyswys

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-11 09:17 UTC, MadMach420 approved these changes

2022-08-11 13:13 UTC, socz3qqq approved these changes

2022-08-12 06:41 UTC, kkkucia approved these changes

2022-08-12 17:14 UTC, MadMach420 requested changes
Wcześniej tego nie zauważyłem, ale merge powinien być na master-C, nie na master.

2022-08-12 17:15 UTC, MadMach420 approved these changes

2022-08-13 21:59 UTC, merged