S3t05
agh-bit-academy/SummerProject2022 pull request #188
Opened 2022-08-10 22:56 UTC by krzyswys

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-12 07:16 UTC, kkkucia requested changes
We wszystkich testach jest order(1) i ja dodałabym dependency.

2022-08-12 18:42 UTC, M0rgho requested changes
1) Testy są bez sensu, zakres liczb nie ma w tym zadaniu znaczenia, liczy się ilość liczb w liście a nie ich zakres. Zakres 10^1000 jest zupełnie niepotrzebny.

2) sol.py mógłby zapisywać tylko 10 największych wartości zamiast wszystkich.

3) Wszystkie markery mają ten sam order.

2022-08-14 09:38 UTC, dadamczykk requested changes

2022-08-14 09:38 UTC, dadamczykk commented on WDI/Zestaw_3/Zadanie_05/sol.py
> +            n = ans[:i] + t + ans[i:]
Rozwiązanie używa dodawania list, które jest nielegalne na wdi (a na pewno nie było w tym zestawie)

2022-08-14 11:55 UTC, closed without merging