Update RandFixArray.py
agh-bit-academy/SummerProject2022 pull request #202
Opened 2022-08-12 15:37 UTC by MadMach420

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-12 17:17 UTC, akarcinski approved these changes

2022-08-12 18:28 UTC, M0rgho approved these changes

2022-08-12 19:50 UTC, Kasl0 approved these changes
Brak komentarza z autorem/autorami pliku, ale w sumie sam nie wiem czy jest tu konieczny

2022-08-13 22:00 UTC, Rusiek requested changes
Operatory nie zwracają tablicy, tylko klasę RFArray.

2022-08-14 13:52 UTC, MadMach420 reviewed
Dodałem nową metodę from_list, tworzy ona nowy obiekt klasy RandFixArray i nadaje __array wartość przekazaną jako argument. Jest to coś, czego potrzeba dosyć często, więc chyba się przyda taka metoda.

2022-08-14 19:40 UTC, closed without merging