Done tests for s3t07
agh-bit-academy/SummerProject2022 pull request #205
Opened 2022-08-12 18:47 UTC by dadamczykk

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-13 20:45 UTC, socz3qqq approved these changes

2022-08-13 21:56 UTC, puszekjuliuszek approved these changes

2022-08-13 21:58 UTC, puszekjuliuszek requested changes
chyba przypadkiem wybrałeś zły branch do mergowania, bo masz wybranego mastera zamiast mastera-B

2022-08-13 22:18 UTC, puszekjuliuszek approved these changes

2022-08-14 08:35 UTC, M0rgho approved these changes

2022-08-14 08:35 UTC, merged