B_s3t16_tests
agh-bit-academy/SummerProject2022 pull request #209
Opened 2022-08-13 14:07 UTC by kkkucia

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-13 15:28 UTC, dadamczykk requested changes

2022-08-13 15:28 UTC, dadamczykk commented on WDI/Zestaw_3/Zadanie_16/test_basic.py
> +class Basic:
Klasy powinny mieć nazwy w stylu Test*, czyli u Ciebie powinno się zmienić icha nazwy: Basic -> TestBasic, BigRandom -> TestBigRandom itp. Inaczej pytest może nie wykrywać testów.

2022-08-13 19:53 UTC, kkkucia commented on WDI/Zestaw_3/Zadanie_16/test_basic.py
> +class Basic:
Poprawione, dzięki :)

2022-08-13 20:10 UTC, socz3qqq requested changes

2022-08-13 20:10 UTC, socz3qqq commented on WDI/Zestaw_3/Zadanie_16/test_smallRand.py
> +@pytest.mark.dependency(name="test_small_s3t16", depends=["test_basic_s3t1"], scope="session")
Tu w depends się 6 na końcu zgubiła, "test_basic_s3t1**6**"

2022-08-14 08:39 UTC, M0rgho submitted a review, later dismissed

2022-08-14 09:33 UTC, dadamczykk submitted a review, later dismissed

2022-08-14 11:43 UTC, puszekjuliuszek submitted a review, later dismissed

2022-08-14 13:54 UTC, MadMach420 submitted a review, later dismissed

2022-08-14 17:34 UTC, merged