C s3t17
agh-bit-academy/SummerProject2022 pull request #211
Opened 2022-08-13 15:56 UTC by VeryLongNicknameSuchWow

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-13 19:37 UTC, akarcinski commented on WDI/Zestaw_3/Zadanie_17/sol.py
> +                break
Garek by się rozpłakał a Falisz by nie wierzył gdyby zobaczyli taką funkcję sprawdzającą pierwszość liczby.
To w ogóle powinno być w osobnej funkcji i jednak robienie tego liniowo nie jest dobrym pomysłem

2022-08-13 20:30 UTC, VeryLongNicknameSuchWow commented on WDI/Zestaw_3/Zadanie_17/sol.py
> +                break
Poprawione

2022-08-14 07:43 UTC, irosikoni submitted a review, later dismissed

2022-08-14 08:59 UTC, M0rgho requested changes

2022-08-14 08:59 UTC, M0rgho commented on WDI/Zestaw_3/Zadanie_17/sol.py
> +    return True
Można by osobno sprawdzić podzielność dla 2 i zacząć od factor = 3, a w pętli factor += 2.

2022-08-14 09:45 UTC, dadamczykk submitted a review, later dismissed

2022-08-14 10:39 UTC, kkkucia approved these changes

2022-08-14 10:41 UTC, akarcinski approved these changes

2022-08-14 12:28 UTC, VeryLongNicknameSuchWow commented on WDI/Zestaw_3/Zadanie_17/sol.py
> +    return True
Poprawiłem na bardziej zoptymalizowaną wersję z BIT algo

2022-08-14 13:58 UTC, MadMach420 approved these changes

2022-08-14 17:33 UTC, merged