s3t06
agh-bit-academy/SummerProject2022 pull request #214
Opened 2022-08-13 19:05 UTC by akarcinski

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-13 20:39 UTC, socz3qqq requested changes

2022-08-13 20:39 UTC, socz3qqq commented on WDI/Zestaw_3/Zadanie_06/test_bigRand.py
> +@pytest.mark.dependency(name="test_bigRand_s3t06", depend=["test_smallRand_s3t06"], scope="session")
depend**s** zamiast depend

2022-08-13 20:39 UTC, socz3qqq commented on WDI/Zestaw_3/Zadanie_06/prog.py
> +    pass
Dołóż tą pustą linię w każdym pliku

2022-08-13 20:39 UTC, socz3qqq commented on WDI/Zestaw_3/Zadanie_06/check.py
> +    return True
- Pusta linia na końcu

2022-08-13 20:39 UTC, socz3qqq commented on WDI/Zestaw_3/Zadanie_06/DATA.txt
> +15
Czas powinien we floatach być

2022-08-13 20:39 UTC, socz3qqq commented on WDI/Zestaw_3/Zadanie_06/DATA.txt
> +1
Są dwa testy nie jeden

2022-08-14 10:10 UTC, akarcinski commented on WDI/Zestaw_3/Zadanie_06/prog.py
> +    pass
Dziwne bo flake8 tego nie wyłapał a zwykle wyłapuje, dzięki

2022-08-14 11:40 UTC, puszekjuliuszek submitted a review, later dismissed

2022-08-14 11:53 UTC, M0rgho submitted a review, later dismissed

2022-08-14 11:59 UTC, kkkucia approved these changes

2022-08-14 14:04 UTC, MadMach420 approved these changes

2022-08-14 17:32 UTC, merged