S311 test fix
agh-bit-academy/SummerProject2022 pull request #217
Opened 2022-08-14 12:01 UTC by krzyswys

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-14 12:29 UTC, M0rgho commented on WDI/Zestaw_3/Zadanie_11/test_big.py
> +    t = [A * R ** (n - 1) for n in range(1, LGT)]
R ** LGT jest stanowczo za duże, powstała liczba zajmuje ponad 1kB pamięci, proponuję zmienić zakres R do <2, 30>.

2022-08-17 13:50 UTC, akarcinski requested changes
nie wiadomo co w testach oznaczają literki A, R, LGT

2022-08-17 14:55 UTC, krzyswys commented
> nie wiadomo co w testach oznaczają literki A, R, LGT

LGT, jak umiejscowienie w kodzie wskazuje (przy pętli)  - odpowiada za długość tablicy t, czyli całkowitą długość generowanego szeregu geometrycznego.
A, R to raczej standardowe oznaczenia we wzorze na kolejne wyrazy szeregu geometrycznego, a przynajmniej ja się z takimi spotkałem.
Nie za bardzo rozumiem które oznaczenia byłyby na tyle bardziej czytelne że byłby sens to zmieniać, dlatego też prosiłbym o jakąś propozycję w zamian

2022-08-17 15:41 UTC, akarcinski approved these changes

2022-08-19 16:12 UTC, ksew1 approved these changes

2022-08-19 16:54 UTC, Rusiek approved these changes

2022-08-19 16:54 UTC, merged