B s4t8
agh-bit-academy/SummerProject2022 pull request #249
Opened 2022-08-22 09:08 UTC by puszekjuliuszek

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-22 09:30 UTC, NiEkOKsU approved these changes

2022-08-22 15:58 UTC, kkkucia submitted a review, later dismissed

2022-08-22 17:04 UTC, ksew1 submitted a review, later dismissed

2022-08-23 19:44 UTC, socz3qqq requested changes

2022-08-23 19:44 UTC, socz3qqq commented on WDI/Zestaw_4/Zadanie_08/sol.py
> +            col += 1
tutaj chyba leng = 2, albo usunąć row += 1  i col += 1, bo np dla tablicy: [[2, 1, 1, 1, 1, 1, 2],
              [1, 4, 1, 1, 1, 2, 2],
              [1, 1, 8, 1, 2, 2, 1],
              [1, 1, 2, 2, 2, 1, 1],
              [1, 1, 2, 2, 4, 1, 1],
              [1, 2, 3, 2, 1, 8, 1],
              [2, 3, 1, 2, 1, 1, 16]
]
zwraca 3 a powinno zwrócić 4

2022-08-26 21:06 UTC, puszekjuliuszek commented on WDI/Zestaw_4/Zadanie_08/sol.py
> +            col += 1
rzeczywiście, nie zauważyłem tego, już zmieniam

2022-08-27 13:42 UTC, puszekjuliuszek commented
funfact, że działało tylko usunięcie tego row += 1 col += 1, podstawianie leng = 2 w innych testach dawało złe wyniki

2022-08-27 15:21 UTC, dadamczykk approved these changes

2022-08-27 17:22 UTC, kkkucia approved these changes

2022-08-29 08:42 UTC, socz3qqq approved these changes

2022-08-30 07:47 UTC, NiEkOKsU approved these changes

2022-08-30 07:47 UTC, merged