zad16_zestaw4
agh-bit-academy/SummerProject2022 pull request #250
Opened 2022-08-22 19:05 UTC by DroppedHard

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-22 22:53 UTC, DroppedHard commented
Proszę sprawdźcie czy RandFixArray działa poprawnie, bo u mnie wyskakiwały błędy. Mam identycznie jak zadanie wcześniej i dalej nie pomaga.

2022-08-24 15:43 UTC, MadMach420 requested changes
Błąd nie był w imporcie, tylko w braku \_\_init\_\_.py. Po dodaniu działa.

Edit: w sumie sam dodam po PR już 2 dni ma

2022-08-24 15:45 UTC, MadMach420 approved these changes

2022-08-24 15:52 UTC, kkkucia submitted a review, later dismissed

2022-08-25 17:11 UTC, dadamczykk approved these changes

2022-08-28 14:01 UTC, puszekjuliuszek commented
A w sumie nie brakuje DATA.txt?

2022-08-29 08:59 UTC, socz3qqq commented on WDI/Zestaw_4/Zadanie_16/test_big.py
> +def test_big(self, data):
Wywala błąd, zbędny self

2022-08-29 09:01 UTC, socz3qqq requested changes

2022-08-29 09:01 UTC, socz3qqq commented on WDI/Zestaw_4/Zadanie_16/test_big.py
> +def test_big(self, data):
wywala błąd, zbędny self

2022-08-29 09:01 UTC, socz3qqq commented on WDI/Zestaw_4/Zadanie_16/test_basic.py
> +@pytest.mark.dependency(name="test_basic_s4t15", scope="session")
Literówka w name, przez co drugi test jest zawsze skipowany, powinno być name="test_basic_s4t1**6**"

2022-09-02 22:22 UTC, krzyswys reviewed
Prog.py powinien chyba pozostać pusty żeby ktoś nie zaspojlerował sobie odpowiedzi od razu

2022-09-22 12:37 UTC, irosikoni commented
pozwolilam sobie popoprawiac, bo PR ma juz miesiac

2022-09-22 17:45 UTC, socz3qqq approved these changes

2022-09-24 16:29 UTC, puszekjuliuszek approved these changes

2022-09-24 16:29 UTC, merged