s4t17_test
agh-bit-academy/SummerProject2022 pull request #252
Opened 2022-08-23 08:48 UTC by kkkucia

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-08-23 11:56 UTC, NiEkOKsU approved these changes

2022-08-23 15:26 UTC, ksew1 submitted a review, later dismissed

2022-08-23 17:01 UTC, dadamczykk requested changes
Skoro program może zwrócić dowolną parę, (x, y) (o której mowa w zadaniu), to rozwiązanie użytkownika może dać inny wynik, niż rozwiązanie z sol.py. Proponuję, żeby zrobić funkcję  (np check()) zwracającą tablicę z wszystkimi parami mającymi największą sumę i zrobić assert user_sol(data) in check(data)

2022-08-23 17:43 UTC, dadamczykk commented on WDI/Zestaw_4/Zadanie_17/test_basic.py
> +    [[2, 2], [2, 2]]
brakuje przecinka

2022-08-24 10:06 UTC, kkkucia commented on WDI/Zestaw_4/Zadanie_17/test_basic.py
> +    [[2, 2], [2, 2]]
Poprawiłam i uwzględniłam poprzedni komentarz ;)

2022-08-24 15:49 UTC, MadMach420 approved these changes

2022-08-24 16:31 UTC, dadamczykk approved these changes

2022-08-24 16:40 UTC, NiEkOKsU approved these changes

2022-08-24 17:27 UTC, socz3qqq approved these changes

2022-08-24 17:28 UTC, merged