S6 t10
agh-bit-academy/SummerProject2022 pull request #295
Opened 2022-09-10 12:12 UTC by irosikoni

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-09-11 17:55 UTC, NiEkOKsU approved these changes

2022-09-12 16:26 UTC, Kasl0 requested changes
Pytest się wywala na testach
![gsef](https://user-images.githubusercontent.com/109617866/189706359-5c729e54-7203-4e0d-b26f-6f3f45b1c570.PNG)

2022-09-13 19:43 UTC, puszekjuliuszek approved these changes

2022-09-13 20:09 UTC, Kasl0 approved these changes

2022-09-13 20:10 UTC, merged