S6 t28
agh-bit-academy/SummerProject2022 pull request #296
Opened 2022-09-10 12:43 UTC by irosikoni

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-09-11 21:46 UTC, socz3qqq requested changes
Ogólnie wszystko git, tylko w DATA.txt jest sam template

2022-09-12 16:36 UTC, Kasl0 requested changes
Pytest się wywala na testach
![pytest](https://user-images.githubusercontent.com/109617866/189708266-c8be6b91-1fe9-4d9c-9f82-1a0cf3249f56.PNG)
Flake8 zgłasza kilka kosmetycznych zmian
![flake8](https://user-images.githubusercontent.com/109617866/189708379-39ef32f9-5c3d-4c02-ba41-ac6f7bf4e0a0.PNG)

2022-09-13 19:56 UTC, puszekjuliuszek commented on WDI/Zestaw_6/Zadanie_28/DATA.txt
> +2
to chyba powinien być float

2022-09-13 19:56 UTC, puszekjuliuszek commented on WDI/Zestaw_6/Zadanie_28/test_bigger.py
> +TEST_NUM = 15
czy Tobie te testy przechodzą w jakimś sensownym czasie? bo u mnie pierwszy test z big chyba z 5 minut szedł i nie doszedł tylko to ja się poddałem. Tak myślę, że to może kwestia mojego wolnego laptopa i zbyt wyżyłowanych testów, ale no nwm, tylko Ci to daję pod rozwagę

2022-09-13 20:11 UTC, puszekjuliuszek commented
a i możesz się zastanowić nad dopracowaniem generowania testów, bo wszystkie które nie są napisane z palca dają False i to też nie do końca dobrze sprawdza czy ktoś dobrze zrobił prog.py, bo return False Ci zaliczy prawie wszystkie testy. Może to już zauważyłaś, ale średnio jest jak te testy zmienić bo też miałem takie sytuacje, natomiast jeśli masz czas i pomysł to możesz tam coś zmienić

2022-09-13 20:16 UTC, Kasl0 commented on WDI/Zestaw_6/Zadanie_28/test_bigger.py
> +TEST_NUM = 15
Odpaliłem u siebie i mam to samo, a mój komputer nie jest jakiś wolny :/

2022-09-15 09:39 UTC, irosikoni commented
Nie mam pomysłu jak zrobić żeby czasem dawały true, a nie false, jeśli ktoś ma coś to może poprawić/podpowiedzieć

2022-09-15 19:46 UTC, Kasl0 approved these changes

2022-09-16 15:01 UTC, puszekjuliuszek approved these changes

2022-09-18 15:42 UTC, puszekjuliuszek approved these changes

2022-09-19 09:31 UTC, socz3qqq requested changes

2022-09-19 09:31 UTC, socz3qqq commented on WDI/Zestaw_6/Zadanie_28/sol.py
> +        return False
Jeśli dobrze rozumiem zadanie, to trzeba tą tablicę podzielić na dokładnie 3 zbiory, tak żeby wszystkie liczby z tablicy były wykorzystane, więc linijki 11 - 14, powinny np. wyglądać tak:
```
if i == len(T):
    if sum1 == sum2 == sum3 != 0:
        return True
    return False
```
aktualnie np. f(T = [5, 5, 5, 1]) zwraca True

2022-09-19 09:31 UTC, socz3qqq commented on WDI/Zestaw_6/Zadanie_28/test_basic.py
> +print(generate(MIN_RANGE, MAX_RANGE, L_RANGE, R_RANGE))
zbędny print

2022-09-19 21:00 UTC, puszekjuliuszek commented on WDI/Zestaw_6/Zadanie_28/test_basic.py
> +print(generate(MIN_RANGE, MAX_RANGE, L_RANGE, R_RANGE))
a zapomniałem go wywalić, dzięki, niedługo ogarnę

2022-09-19 21:02 UTC, puszekjuliuszek commented on WDI/Zestaw_6/Zadanie_28/sol.py
> +        return False
wiesz co, też na to zwróciłem uwagę, ale imo treść nie mówi o tym wprost, a jedynie przykład to sugeruje, no bo tam jest tak:
"""
Prosze napisac funkcje, która zwraca informacje, czy jest mozliwy podział zbioru N liczb na trzy podzbiory, tak aby w kazdym podzbiorze, łaczna liczba jedynek uzyta do zapisu elementów tego podzbioru w systemie dwójkowym była jednakowa.
"""
jak dla mnie to tak jak Iza napisała jest ok

2022-09-19 21:21 UTC, puszekjuliuszek commented on WDI/Zestaw_6/Zadanie_28/sol.py
> +        return False
to prawda, tutaj ten if ma zły warunek, ale ja bym to napisał w ten sposób:
    if i == len(T) and (sum1 == sum2 == sum3 != 0):
        return True
    if i == len(T):
        return False
może to w sumie znaczy to samo co napisałeś

2022-09-20 10:57 UTC, irosikoni commented on WDI/Zestaw_6/Zadanie_28/sol.py
> +        return False
poprawione

2022-09-20 14:32 UTC, puszekjuliuszek approved these changes

2022-09-20 16:21 UTC, socz3qqq approved these changes

2022-09-21 20:04 UTC, merged