A s1t5
agh-bit-academy/SummerProject2022 pull request #30
Opened 2022-08-02 19:03 UTC by MadMach420

# PR Template
## Lista zmian
### Lista dodanych plików + uzasadnienie
- DATA.txt
- test_basic.py
- test_bigRandom
- sol.py, init.py, prog.py

### Lista zmodyfikowanych plików + uzasadnienie
- sporo zmienionych przez Rusiek, z jakiegoś powodu chyba A ma starszą wersję plików, mogą przez to być pewnie problemy w przyszłości

### Lista dodanych testów + opis testów
- test_basic w test_basic.py - wybrane 10 liczb sprawdzające czy w ogóle działa
- test_random w test_basic - małe testy
- test_mid w test_bigRandom - średnie testy (przedział 10 ** 6 - 10 ** 8)
- test_big w test_bigRandom - duże testy (przedział 10 ** 8 - 10 ** 10)

## Lista Wymagań
### Ogólna lista wymagań
- [ ] flake8
- [ ] Pliki odnoszą się do odpowiedniego katalogu
- [ ] Brak "Magic Number"
- [ ] Komentarz zawierający listę autorów dla niepustych plików

### Lista wymagań dla testów
- [ ] Uruchomienie przez *core.py*
- [ ] Uruchomienie przez pytest *nazwa_pliku.py*
- [ ] Dodanie plików DATA.txt i \_\_init\_\_.py

### Lista wymagań dla plików źródłowych
- [ ] Napisanie testów dla funkcji oraz metod w klasach
- [ ] Oznaczenie otestowanych funkcji oraz metod w klasach
- [ ] Samodokumentujące się zmienne oraz funkcje
- [ ] Import *nazwa* -> from *nazwa* import *nazwa1*, *nazwa2*, ...
- [ ] Import w kolejności alfabetycznej bibliotek  

### Nazewnictwo 
- [ ] Makra -> PIERWSZE_DRUGIE_TRZECIE
- [ ] Zmienne -> pierwszeDrugieTrzecie
- [ ] Funkcje -> pierwsze_drugie_trzecie
- [ ] Klasy -> PierwszeDrugieTrzecie
- [ ] Pliki -> pierwsze_drugie_trzecie
- [ ] Katalogi -> Pierwsze_Drugie_Trzecie

### pytest
- [ ] Kolejność markerów: order -> dependency -> parametrize
- [ ] Jeżeli możliwe, markery *order* i *dependency* przy klasie
- [ ] Marker *parametrize* przy funkcji
- [ ] Pliki -> test_pierwszeDrugieTrzecie
- [ ] Funkcje -> test_pierwsze_drugie_trzecie
- [ ] Klasy -> TestPierwszeDrugieTrzecie
- [ ] Listy testów -> pierwszeDrugieTrzecieTests
- [ ] Dependency_name -> test\[*nazwa_pliku*\]_\[s..t..\]
- [ ] Nazwa funkcji zawiera analogiczny człon jak testy w markerze parametrize

2022-08-02 19:29 UTC, Rusiek requested changes
Kilka zmian, raczej nie dajemy w klasie dependency

2022-08-02 19:29 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_05/test_basic.py
> +"""
Drugą możliwością było zrobienie tego w listach

2022-08-02 19:29 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_05/test_bigRandom.py
> +bigRandomTests = [(randint(MIN_RANGE_BIG, MAX_RANGE_BIG),) for _ in range(NO_OF_TESTS)]
Zmień zakres MAX_RANGE_BIG na 10 ** 9, ze później psuje się dokładność i niektóre programy mogą wpaść w nieskończoną pętlę przez takie testy

2022-08-02 19:29 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_05/test_bigRandom.py
> +    @pytest.mark.dependency()
Pusty marker niczego nie zrobi

2022-08-02 19:29 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_05/test_bigRandom.py
> +    @pytest.mark.dependency(depends=["test_mid"], scope="class")
Prawdopodobnie przez pusty marker wyżej test nie zostanie wykonany niezależnie od wyniku testu wyżej

2022-08-02 19:29 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_05/test_bigRandom.py
> +MAX_RANGE_MID = 10 ** 8
Proponuję trochę mniejsze liczby w teście midRandomTests

2022-08-02 19:30 UTC, Rusiek requested changes
To nie jest wyznaczanie pierwiastka kwadratowego ze wzoru Newtona

2022-08-03 09:59 UTC, MadMach420 commented on WDI/Zestaw_1/Zadanie_05/test_basic.py
> +"""
Chyba działałoby tak samo, zostawiam krotki

2022-08-03 09:59 UTC, MadMach420 commented on WDI/Zestaw_1/Zadanie_05/test_bigRandom.py
> +bigRandomTests = [(randint(MIN_RANGE_BIG, MAX_RANGE_BIG),) for _ in range(NO_OF_TESTS)]
Zmienione

2022-08-03 10:00 UTC, MadMach420 commented on WDI/Zestaw_1/Zadanie_05/test_bigRandom.py
> +    @pytest.mark.dependency()
Robiłem to według dokumentacji (https://pytest-dependency.readthedocs.io/en/stable/usage.html) i działało w sumie bezproblemowo, i przy odpaleniu przez pytest, i przy core.py, ale i tak usunę bo w sumie dodałem to żeby poeksperymentować.

2022-08-03 10:00 UTC, MadMach420 commented on WDI/Zestaw_1/Zadanie_05/test_bigRandom.py
> +    @pytest.mark.dependency(depends=["test_mid"], scope="class")
Jak wyżej, usuwam.

2022-08-03 10:01 UTC, MadMach420 commented on WDI/Zestaw_1/Zadanie_05/test_bigRandom.py
> +MAX_RANGE_MID = 10 ** 8
Zmniejszone o rząd wielkości

2022-08-03 10:04 UTC, MadMach420 commented
Myślałem, że funkcja sprawdzająca ma tylko sprawdzić poprawność funkcji użytkownika, a nie zaimplementować ją drugi raz, ale i tak zmieniłem. Na przyszłość będzie wiadomo.

2022-08-03 12:51 UTC, Rusiek commented
Jeżeli return x ** 2 było w prog.py, to mój błąd, było ok w takim wypadku

2022-08-03 12:53 UTC, Rusiek reviewed
Jedna poprawka i git

2022-08-03 12:53 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_05/sol.py
> +APPROX_ERROR = 10 ** (-6)
W plikach sol.py nie dajemy mark, są nieczytelne dla niedoświadczonej osoby, makra dajemy w klasach i testach

2022-08-03 14:23 UTC, merged

2022-08-03 14:31 UTC, Rusiek reviewed
Ok