sol and prog finished
agh-bit-academy/SummerProject2022 pull request #307
Opened 2022-09-18 13:35 UTC by irosikoni

## Lista Wymagań
- [ ] flake8
- [ ] Komentarz zawierający listę autorów dla niepustych plików
- [ ] git pull --rebase
- [ ] Uruchomienie pytest na testach
- [ ] Order -> Dependency -> Parameterize

2022-09-18 22:08 UTC, socz3qqq requested changes

2022-09-18 22:08 UTC, socz3qqq commented on WDI/Zestaw_6/Zadanie_32/sol.py
> +        if i == len(T) - 1:
Tutaj chyba powinno być ` if  i == len(T)`, bo aktualnie nie sprawdzasz ostatniej liczby w tablicy. Np  f([1, 1], 2) zwraca False, a powinno True

2022-09-20 16:49 UTC, socz3qqq approved these changes

2022-09-24 16:43 UTC, puszekjuliuszek reviewed
zastanawiam się, czy nie wygodniej by było DATA.txt wrzucić dopiero z testami, bo takto będziesz musiała to nadpisywać i rozwiązywać konflikty, ale to tylko pytam, bo jak tak ma być to od razu pyknę approva

2022-09-26 16:35 UTC, puszekjuliuszek approved these changes

2022-09-26 16:35 UTC, merged