B s2t16 test
agh-bit-academy/SummerProject2022 pull request #35
Opened 2022-08-02 22:39 UTC by Nepommuck

# PR Template
## Lista zmian
### Lista dodanych plików + uzasadnienie
**Testy:**
-Zestaw_2/Zadanie_16/test_basic.py
-Zestaw_2/Zadanie_16/test_mid.py
-Zestaw_2/Zadanie_16/test_big.py
-Zestaw_2/Zadanie_16/test_fundamental.py

-Zestaw_2/Zadanie_16/gener_sol.py - generuje rozwiązanie testu z pliku sol.txt
-Zestaw_2/Zadanie_16/sol.txt - spamiętane rozwiązanie
-Zestaw_2/Zadanie_16/prog.py - umieściłem przykładowe rozwiązanie żeby sprawdzić szybkość testów

-Zestaw_2/Zadanie_16/DATA.txt
-Zestaw_2/Zadanie_16/__init__.py - empty
-Zestaw_2/Zadanie_16/sol.py - empty

### Lista zmodyfikowanych plików + uzasadnienie
-readstdout.py - Tam był problem z tym pustym outputem

### Lista dodanych testów + opis testów
-TestBasic: B. szybki w wykonaniu
-TestMid:  Szybki w wykonaniu
-TestBig: Tutaj zaczyna mielić, więc mniej testów
-TestFundamental: Sprawdza właściwie jako jedyny polecenie jakie Garek ułożył. Strasznie wolny, bo milion był pewnie z myślą o c++, nie pythonie

## Lista Wymagań
### Ogólna lista wymagań
- [ ] flake8
- [ ] Pliki odnoszą się do odpowiedniego katalogu
- [ ] Brak "Magic Number"
- [ ] Komentarz zawierający listę autorów dla niepustych plików

### Lista wymagań dla testów
- [ ] Uruchomienie przez *core.py*
- [ ] Uruchomienie przez pytest *nazwa_pliku.py*
- [ ] Dodanie plików DATA.txt i \_\_init\_\_.py

### Lista wymagań dla plików źródłowych
- [ ] Napisanie testów dla funkcji oraz metod w klasach
- [ ] Oznaczenie otestowanych funkcji oraz metod w klasach
- [ ] Samodokumentujące się zmienne oraz funkcje
- [ ] Import *nazwa* -> from *nazwa* import *nazwa1*, *nazwa2*, ...
- [ ] Import w kolejności alfabetycznej bibliotek  

### Nazewnictwo 
- [ ] Makra -> PIERWSZE_DRUGIE_TRZECIE
- [ ] Zmienne -> pierwszeDrugieTrzecie
- [ ] Funkcje -> pierwsze_drugie_trzecie
- [ ] Klasy -> PierwszeDrugieTrzecie
- [ ] Pliki -> pierwsze_drugie_trzecie
- [ ] Katalogi -> Pierwsze_Drugie_Trzecie

### pytest
- [ ] Kolejność markerów: order -> dependency -> parametrize
- [ ] Jeżeli możliwe, markery *order* i *dependency* przy klasie
- [ ] Marker *parametrize* przy funkcji
- [ ] Pliki -> test_pierwszeDrugieTrzecie
- [ ] Funkcje -> test_pierwsze_drugie_trzecie
- [ ] Klasy -> TestPierwszeDrugieTrzecie
- [ ] Listy testów -> pierwszeDrugieTrzecieTests
- [ ] Dependency_name -> test\[*nazwa_pliku*\]_\[s..t..\]
- [ ] Nazwa funkcji zawiera analogiczny człon jak testy w markerze parametrize

2022-08-03 08:23 UTC, NiEkOKsU approved these changes

2022-08-03 12:43 UTC, Rusiek commented
Czemu ten commit wnosi 30k linii w pliku sol.txt???

2022-08-03 13:44 UTC, Rusiek requested changes
No ten sol.txt to nie przejdzie

2022-08-04 06:47 UTC, Rusiek commented
Będziemy musieli zmienić, żeby w zadaniu należało odpowiedzieć czy zadana liczba jest liczbą Smitha, ponieważ 2 minuty to zdecydowanie za długo i potem przerobić testy

2022-08-05 09:01 UTC, Rusiek requested changes
Za kilka godzin pojawią się przerobione treści zadań, w twoim przypadku będzie to usunięcie pętli od 1 do 10 ** 6 i zostawienie reszty. Niestety trzeba będzie lekko przerobić testy. Przepraszam za zamieszanie

2022-08-05 20:13 UTC, closed without merging