A s1t17
agh-bit-academy/SummerProject2022 pull request #64
Opened 2022-08-03 17:26 UTC by akarcinski

# PR Template
## Lista zmian
### Lista dodanych plików + uzasadnienie
- sol.py

## Lista Wymagań
### Ogólna lista wymagań
- [ ] flake8
- [ ] Pliki odnoszą się do odpowiedniego katalogu
- [ ] Brak "Magic Number"
- [ ] Komentarz zawierający listę autorów dla niepustych plików

### Lista wymagań dla testów
- [ ] Uruchomienie przez *core.py*
- [ ] Uruchomienie przez pytest *nazwa_pliku.py*
- [ ] Dodanie plików DATA.txt i \_\_init\_\_.py

### Lista wymagań dla plików źródłowych
- [ ] Napisanie testów dla funkcji oraz metod w klasach
- [ ] Oznaczenie otestowanych funkcji oraz metod w klasach
- [ ] Samodokumentujące się zmienne oraz funkcje
- [ ] Import *nazwa* -> from *nazwa* import *nazwa1*, *nazwa2*, ...
- [ ] Import w kolejności alfabetycznej bibliotek  

### Nazewnictwo 
- [ ] Makra -> PIERWSZE_DRUGIE_TRZECIE
- [ ] Zmienne -> pierwszeDrugieTrzecie
- [ ] Funkcje -> pierwsze_drugie_trzecie
- [ ] Klasy -> PierwszeDrugieTrzecie
- [ ] Pliki -> pierwsze_drugie_trzecie
- [ ] Katalogi -> Pierwsze_Drugie_Trzecie

### pytest
- [ ] Kolejność markerów: order -> dependency -> parametrize
- [ ] Jeżeli możliwe, markery *order* i *dependency* przy klasie
- [ ] Marker *parametrize* przy funkcji
- [ ] Pliki -> test_pierwszeDrugieTrzecie
- [ ] Funkcje -> test_pierwsze_drugie_trzecie
- [ ] Klasy -> TestPierwszeDrugieTrzecie
- [ ] Listy testów -> pierwszeDrugieTrzecieTests
- [ ] Dependency_name -> test\[*nazwa_pliku*\]_\[s..t..\]
- [ ] Nazwa funkcji zawiera analogiczny człon jak testy w markerze parametrize

2022-08-03 17:29 UTC, NiEkOKsU approved these changes

2022-08-03 19:06 UTC, Rusiek requested changes
Lekkie zmiany kosmetyczne

2022-08-03 19:06 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_17/prog.py
> +ITERATIONS = 10 ** 3
Agresywne makra

2022-08-03 19:06 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_17/sol.py
> +
Zbędne puste linie

2022-08-03 19:06 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_17/test_A.py
> +
Zbędna pusta linia

2022-08-04 06:49 UTC, Rusiek approved these changes
Zostało użyte git pull zamiast git pull --rebase, ogólnie ok

2022-08-04 11:25 UTC, akarcinski commented on WDI/Zestaw_1/Zadanie_17/sol.py
> +
flake8 tak nakazał

2022-08-04 17:45 UTC, Jullija approved these changes

2022-08-05 09:03 UTC, merged