s1t04 sol.py, __init__.py
agh-bit-academy/SummerProject2022 pull request #67
Opened 2022-08-03 17:47 UTC by KubaBiz

## Lista zmian
### Lista dodanych plików + uzasadnienie
__init__.py 
sol.py

## Lista Wymagań
### Ogólna lista wymagań
- [ ] flake8
- [ ] Pliki odnoszą się do odpowiedniego katalogu
- [ ] Brak "Magic Number"
- [ ] Komentarz zawierający listę autorów dla niepustych plików

### Lista wymagań dla testów
- [ ] Uruchomienie przez *core.py*
- [ ] Uruchomienie przez pytest *nazwa_pliku.py*
- [ ] Dodanie plików DATA.txt i \_\_init\_\_.py

### Lista wymagań dla plików źródłowych
- [ ] Napisanie testów dla funkcji oraz metod w klasach
- [ ] Oznaczenie otestowanych funkcji oraz metod w klasach
- [ ] Samodokumentujące się zmienne oraz funkcje
- [ ] Import *nazwa* -> from *nazwa* import *nazwa1*, *nazwa2*, ...
- [ ] Import w kolejności alfabetycznej bibliotek  

### Nazewnictwo 
- [ ] Makra -> PIERWSZE_DRUGIE_TRZECIE
- [ ] Zmienne -> pierwszeDrugieTrzecie
- [ ] Funkcje -> pierwsze_drugie_trzecie
- [ ] Klasy -> PierwszeDrugieTrzecie
- [ ] Pliki -> pierwsze_drugie_trzecie
- [ ] Katalogi -> Pierwsze_Drugie_Trzecie

### pytest
- [ ] Kolejność markerów: order -> dependency -> parametrize
- [ ] Jeżeli możliwe, markery *order* i *dependency* przy klasie
- [ ] Marker *parametrize* przy funkcji
- [ ] Pliki -> test_pierwszeDrugieTrzecie
- [ ] Funkcje -> test_pierwsze_drugie_trzecie
- [ ] Klasy -> TestPierwszeDrugieTrzecie
- [ ] Listy testów -> pierwszeDrugieTrzecieTests
- [ ] Dependency_name -> test\[*nazwa_pliku*\]_\[s..t..\]
- [ ] Nazwa funkcji zawiera analogiczny człon jak testy w markerze parametrize

2022-08-03 17:54 UTC, NiEkOKsU approved these changes

2022-08-03 19:03 UTC, Rusiek requested changes
Zmień zmienne

2022-08-03 19:03 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_04/sol.py
> +    licznik = 0
Pls nie nazwy zmiennych po polsku, zmień na variable albo na var

2022-08-04 15:02 UTC, closed without merging

2022-08-04 15:02 UTC, KubaBiz commented
pomyliłem zbiory