s2t3 sol.py
agh-bit-academy/SummerProject2022 pull request #76
Opened 2022-08-03 20:44 UTC by MicelloK

# PR Template
## Lista zmian
### Lista dodanych plików + uzasadnienie
sol.py
prog.py (temp)
__init__.py
-

### Lista usuniętych plików + uzasadnienie
-
-

### Lista zmodyfikowanych plików + uzasadnienie
-
-

### Lista dodanych testów + opis testów
-
-

### Lista usuniętych testów + uzasadnienie
-
-

### Lista zmodyfikowanych testów + uzasadnienie
-
-

## Lista Wymagań
### Ogólna lista wymagań
- [ ] flake8
- [ ] Pliki odnoszą się do odpowiedniego katalogu
- [ ] Brak "Magic Number"
- [ ] Komentarz zawierający listę autorów dla niepustych plików

### Lista wymagań dla testów
- [ ] Uruchomienie przez *core.py*
- [ ] Uruchomienie przez pytest *nazwa_pliku.py*
- [ ] Dodanie plików DATA.txt i \_\_init\_\_.py

### Lista wymagań dla plików źródłowych
- [ ] Napisanie testów dla funkcji oraz metod w klasach
- [ ] Oznaczenie otestowanych funkcji oraz metod w klasach
- [ ] Samodokumentujące się zmienne oraz funkcje
- [ ] Import *nazwa* -> from *nazwa* import *nazwa1*, *nazwa2*, ...
- [ ] Import w kolejności alfabetycznej bibliotek  

### Nazewnictwo 
- [ ] Makra -> PIERWSZE_DRUGIE_TRZECIE
- [ ] Zmienne -> pierwszeDrugieTrzecie
- [ ] Funkcje -> pierwsze_drugie_trzecie
- [ ] Klasy -> PierwszeDrugieTrzecie
- [ ] Pliki -> pierwsze_drugie_trzecie
- [ ] Katalogi -> Pierwsze_Drugie_Trzecie

### pytest
- [ ] Kolejność markerów: order -> dependency -> parametrize
- [ ] Jeżeli możliwe, markery *order* i *dependency* przy klasie
- [ ] Marker *parametrize* przy funkcji
- [ ] Pliki -> test_pierwszeDrugieTrzecie
- [ ] Funkcje -> test_pierwsze_drugie_trzecie
- [ ] Klasy -> TestPierwszeDrugieTrzecie
- [ ] Listy testów -> pierwszeDrugieTrzecieTests
- [ ] Dependency_name -> test\[*nazwa_pliku*\]_\[s..t..\]
- [ ] Nazwa funkcji zawiera analogiczny człon jak testy w markerze parametrize

2022-08-03 20:47 UTC, MicelloK commented
mamy to pushować na master-team, czy team?

2022-08-03 21:15 UTC, NiEkOKsU commented
na master-team

2022-08-04 06:53 UTC, Rusiek requested changes
Kilka zmian kosmetycznych, został użyty git pull zamiast git pull --rebase

2022-08-04 06:53 UTC, Rusiek commented on WDI/Zestaw_2/Zadanie_3/prog.py
> +
Zbędna pusta linia

2022-08-04 06:53 UTC, Rusiek commented on WDI/Zestaw_2/Zadanie_3/sol.py
> +
Zbędna pusta linia

2022-08-06 00:31 UTC, Rusiek approved these changes

2022-08-06 00:31 UTC, merged