testy do s1t11 ale prog i sol działają godzinę :c
agh-bit-academy/SummerProject2022 pull request #77
Opened 2022-08-03 21:50 UTC by MicelloK

# PR Template
## Lista zmian
### Lista dodanych plików + uzasadnienie
-
-

### Lista usuniętych plików + uzasadnienie
-
-

### Lista zmodyfikowanych plików + uzasadnienie
-
-

### Lista dodanych testów + opis testów
test_stdout.py -> .WDI/Zestaw_1/Zadanie_11
(porównanie wyjścia prog.py i sol.py)

### Lista usuniętych testów + uzasadnienie
-
-

### Lista zmodyfikowanych testów + uzasadnienie
-
-

## Lista Wymagań
### Ogólna lista wymagań
- [ ] flake8
- [ ] Pliki odnoszą się do odpowiedniego katalogu
- [ ] Brak "Magic Number"
- [ ] Komentarz zawierający listę autorów dla niepustych plików

### Lista wymagań dla testów
- [ ] Uruchomienie przez *core.py*
- [ ] Uruchomienie przez pytest *nazwa_pliku.py*
- [ ] Dodanie plików DATA.txt i \_\_init\_\_.py

### Lista wymagań dla plików źródłowych
- [ ] Napisanie testów dla funkcji oraz metod w klasach
- [ ] Oznaczenie otestowanych funkcji oraz metod w klasach
- [ ] Samodokumentujące się zmienne oraz funkcje
- [ ] Import *nazwa* -> from *nazwa* import *nazwa1*, *nazwa2*, ...
- [ ] Import w kolejności alfabetycznej bibliotek  

### Nazewnictwo 
- [ ] Makra -> PIERWSZE_DRUGIE_TRZECIE
- [ ] Zmienne -> pierwszeDrugieTrzecie
- [ ] Funkcje -> pierwsze_drugie_trzecie
- [ ] Klasy -> PierwszeDrugieTrzecie
- [ ] Pliki -> pierwsze_drugie_trzecie
- [ ] Katalogi -> Pierwsze_Drugie_Trzecie

### pytest
- [ ] Kolejność markerów: order -> dependency -> parametrize
- [ ] Jeżeli możliwe, markery *order* i *dependency* przy klasie
- [ ] Marker *parametrize* przy funkcji
- [ ] Pliki -> test_pierwszeDrugieTrzecie
- [ ] Funkcje -> test_pierwsze_drugie_trzecie
- [ ] Klasy -> TestPierwszeDrugieTrzecie
- [ ] Listy testów -> pierwszeDrugieTrzecieTests
- [ ] Dependency_name -> test\[*nazwa_pliku*\]_\[s..t..\]
- [ ] Nazwa funkcji zawiera analogiczny człon jak testy w markerze parametrize

2022-08-04 06:46 UTC, Rusiek requested changes
Kilka małych poprawek estetycznych, zostało użyte "git pull" zamiast "git pull --rebase"

2022-08-04 06:46 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_11/prog.py
> +            print(num, sum)
Brak końca linii

2022-08-04 06:46 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_11/sol.py
> +
Niepotrzebna przerwa

2022-08-04 06:46 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_11/prog.py
> +    def dziel(num):
Tylko nie nazywaj niczego po polsku w innych plikach, pls

2022-08-04 08:23 UTC, MicelloK commented on WDI/Zestaw_1/Zadanie_11/prog.py
> +    def dziel(num):
W sumie to wszystko nie moje, wziąłem z repo i dodałem tylko testy. W sumie nie wiem czemu to się zcommitowalo

2022-08-04 09:55 UTC, Rusiek commented on WDI/Zestaw_1/Zadanie_11/prog.py
> +    def dziel(num):
A zrobiłeś git pull czy git pull --rebase?

2022-08-06 00:30 UTC, Rusiek approved these changes

2022-08-06 00:30 UTC, merged