B s1t9 sol
agh-bit-academy/SummerProject2022 pull request #81
Opened 2022-08-04 12:49 UTC by puszekjuliuszek

# PR Template
## Lista zmian
### Lista dodanych plików + uzasadnienie
-sol.py
-

### Lista usuniętych plików + uzasadnienie
-
-

### Lista zmodyfikowanych plików + uzasadnienie
-
-

### Lista dodanych testów + opis testów
-
-

### Lista usuniętych testów + uzasadnienie
-
-

### Lista zmodyfikowanych testów + uzasadnienie
-
-

## Lista Wymagań
### Ogólna lista wymagań
- [ ] flake8
- [ ] Pliki odnoszą się do odpowiedniego katalogu
- [ ] Brak "Magic Number"
- [ ] Komentarz zawierający listę autorów dla niepustych plików

### Lista wymagań dla testów
- [ ] Uruchomienie przez *core.py*
- [ ] Uruchomienie przez pytest *nazwa_pliku.py*
- [ ] Dodanie plików DATA.txt i \_\_init\_\_.py

### Lista wymagań dla plików źródłowych
- [ ] Napisanie testów dla funkcji oraz metod w klasach
- [ ] Oznaczenie otestowanych funkcji oraz metod w klasach
- [ ] Samodokumentujące się zmienne oraz funkcje
- [ ] Import *nazwa* -> from *nazwa* import *nazwa1*, *nazwa2*, ...
- [ ] Import w kolejności alfabetycznej bibliotek  

### Nazewnictwo 
- [ ] Makra -> PIERWSZE_DRUGIE_TRZECIE
- [ ] Zmienne -> pierwszeDrugieTrzecie
- [ ] Funkcje -> pierwsze_drugie_trzecie
- [ ] Klasy -> PierwszeDrugieTrzecie
- [ ] Pliki -> pierwsze_drugie_trzecie
- [ ] Katalogi -> Pierwsze_Drugie_Trzecie

### pytest
- [ ] Kolejność markerów: order -> dependency -> parametrize
- [ ] Jeżeli możliwe, markery *order* i *dependency* przy klasie
- [ ] Marker *parametrize* przy funkcji
- [ ] Pliki -> test_pierwszeDrugieTrzecie
- [ ] Funkcje -> test_pierwsze_drugie_trzecie
- [ ] Klasy -> TestPierwszeDrugieTrzecie
- [ ] Listy testów -> pierwszeDrugieTrzecieTests
- [ ] Dependency_name -> test\[*nazwa_pliku*\]_\[s..t..\]
- [ ] Nazwa funkcji zawiera analogiczny człon jak testy w markerze parametrize

2022-08-04 12:56 UTC, NiEkOKsU commented
Chyba chcesz to na master-team puszować a nie na zwykłego mastera

2022-08-04 13:03 UTC, NiEkOKsU commented on WDI/Zestaw_1/Zadanie_09/sol.py
> +        stack = []
Nwm jak z tą tablicą bo to jest git, ale nie w pierwszych zestawach, dla niektórych prowadzących, szczególnie że potem jeszcze robisz .pop z nią co już by na pewno nie przeszło jako wzorcówka dla pierwszaków na 1 zestaw, w skrócie, gdyby to nie było wdi to spoko, ale to jest wdi więc chyba nie do końca wg. mnie

2022-08-04 13:14 UTC, Rusiek requested changes
W zestawach 1, 2 nie było wprowadzonych jeszcze tablic

2022-08-04 14:44 UTC, puszekjuliuszek commented
Uprościłem to rozwiązanie, bo szczerze mówiąc, żeby wypisać rosnąco te liczby bez tablic i zachować złożoność O(sqrt(n)) to nie mam pojęcia jak to zrobić

2022-08-04 19:50 UTC, akarcinski approved these changes

2022-08-05 09:13 UTC, Rusiek commented
Robisz push na mastera, powinieneś na master-X. Zamykam

2022-08-05 09:13 UTC, closed without merging