E s2t04 sol.py, __init__.py
agh-bit-academy/SummerProject2022 pull request #84
Opened 2022-08-04 15:09 UTC by KubaBiz

## Lista zmian
### Lista dodanych plików + uzasadnienie
- sol.py <- WDI\Zestaw_1\Zadanie_04
- __init__.py <- WDI\Zestaw_1\Zadanie_04

## Lista Wymagań
### Ogólna lista wymagań
- [ ] flake8
- [ ] Pliki odnoszą się do odpowiedniego katalogu
- [ ] Brak "Magic Number"
- [ ] Komentarz zawierający listę autorów dla niepustych plików

### Lista wymagań dla testów
- [ ] Uruchomienie przez *core.py*
- [ ] Uruchomienie przez pytest *nazwa_pliku.py*
- [ ] Dodanie plików DATA.txt i \_\_init\_\_.py

### Lista wymagań dla plików źródłowych
- [ ] Napisanie testów dla funkcji oraz metod w klasach
- [ ] Oznaczenie otestowanych funkcji oraz metod w klasach
- [ ] Samodokumentujące się zmienne oraz funkcje
- [ ] Import *nazwa* -> from *nazwa* import *nazwa1*, *nazwa2*, ...
- [ ] Import w kolejności alfabetycznej bibliotek  

### Nazewnictwo 
- [ ] Makra -> PIERWSZE_DRUGIE_TRZECIE
- [ ] Zmienne -> pierwszeDrugieTrzecie
- [ ] Funkcje -> pierwsze_drugie_trzecie
- [ ] Klasy -> PierwszeDrugieTrzecie
- [ ] Pliki -> pierwsze_drugie_trzecie
- [ ] Katalogi -> Pierwsze_Drugie_Trzecie

### pytest
- [ ] Kolejność markerów: order -> dependency -> parametrize
- [ ] Jeżeli możliwe, markery *order* i *dependency* przy klasie
- [ ] Marker *parametrize* przy funkcji
- [ ] Pliki -> test_pierwszeDrugieTrzecie
- [ ] Funkcje -> test_pierwsze_drugie_trzecie
- [ ] Klasy -> TestPierwszeDrugieTrzecie
- [ ] Listy testów -> pierwszeDrugieTrzecieTests
- [ ] Dependency_name -> test\[*nazwa_pliku*\]_\[s..t..\]
- [ ] Nazwa funkcji zawiera analogiczny człon jak testy w markerze parametrize

2022-08-04 16:47 UTC, NiEkOKsU approved these changes

2022-08-04 17:44 UTC, Jullija approved these changes

2022-08-05 09:11 UTC, Rusiek requested changes
Spoko, jedna zmiana kosmetyczna i git

2022-08-05 09:11 UTC, Rusiek commented on WDI/Zestaw_2/Zadanie_04/sol.py
> +        pom = i
Może zmień na help_var czy coś w tym stylu? Bo pom wygląda dziwnie tbh

2022-08-05 14:16 UTC, KubaBiz commented on WDI/Zestaw_2/Zadanie_04/sol.py
> +        pom = i
jasne, złe nawyki po wdi i asd XD

2022-08-05 19:47 UTC, socz3qqq approved these changes
Git, ale imo czytelniej by było jakby zamiast ifów były while i na końcu tylko sprawdzenie if help_var == 1: variable +=1

2022-08-06 00:09 UTC, Rusiek approved these changes

2022-08-06 00:09 UTC, merged